version: '3.8'

services:

  flask-hadoop-app:
    image: flask-hadoop-app
    container_name: flask-hadoop-app
    build:
      context: .
      dockerfile: ./app.Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 'True'
      DATABASE_URI: ${DEV_DATABASE_URI}
    networks:
      - flask-hadoop-app-network
    restart: on-failure
    deploy:
      replicas: 1

  hadoop-app:
    image: hadoop-app
    container_name: hadoop-app
    build:
      context: .
      dockerfile: ./hadoop.Dockerfile
    ports:
      - 8088:8088
    networks:
      - flask-hadoop-app-network
    restart: on-failure
    deploy:
      replicas: 1

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok
    ports:
      - "4040:4040"
    networks:
      - flask-hadoop-app-network
    env_file: .env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "flask-hadoop-app:5000"]

networks:
    flask-hadoop-app-network:
      driver: bridge
      name: flask-hadoop-app-network
